# For more info on HTTP files go to https://aka.ms/vs/httpfile

@server = https://localhost:7150

GET {{server}}/v1/Joke

###
GET {{server}}/v1/Joke/TimesTold/Tree%20Joke


###

POST {{server}}/v1/Joke
Content-Type: application/json

{
  "id": 69,
  "jokename": "testJoke",
  "joketext": "Funny joke jajaja",
  "categorizedjokes": [],
  "deliveredjokes": []
}

